// Generated by CoffeeScript 1.4.0
(function() {
  var Brain;

  Brain = (function() {

    function Brain(title, description) {
      this.title = title != null ? title : 'Title';
      this.description = description != null ? description : 'Description';
    }

    Brain.prototype.getTemplate = function(name) {
      var Ajax;
      Ajax = null;
      if (window.XMLHttpRequest) {
        Ajax = new XMLHttpRequest();
      } else {
        Ajax = new ActiveXObject("Microsoft.XMLHTTP");
      }
      if (Ajax) {
        Ajax.open('get', 'templates/' + name, false);
        Ajax.send();
        return Ajax.responseText;
      } else {
        throw 'Ajax not supported';
      }
      return false;
    };

    Brain.prototype.about = function() {
      return this.getTemplate('about.html');
    };

    Brain.prototype.nyanCat = function() {
      return this.getTemplate('nyan_cat.html');
    };

    return Brain;

  })();

  window.Brain = Brain;

  $(function() {
    var brain, terminal_cmd;
    brain = new Brain('Nedim Arabacı', 'Hi, this is my term (type help for help) [up|down: history, tab: autocomplete]');
    terminal_cmd = $('#terminal_cmd');
    terminal_cmd.Termic('#terminal', {
      '__init__': {
        description: 'Term init.',
        handler: function() {
          this.set('brain', brain);
          return "" + (this.get('brain').title) + " - " + (this.get('brain').description);
        }
      },
      'about': {
        description: 'About me',
        handler: function() {
          return this.get('brain').about();
        }
      },
      'nyan': {
        description: 'Nyan cat',
        handler: function(params) {
          this.runCommand('clear', params);
          return this.get('brain').nyanCat();
        }
      }
    });
    return terminal_cmd.focus();
  });

}).call(this);
