// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = jQuery;

  $.fn.Termic = function(terminal, commands) {
    var $el, $terminal;
    $el = $(this);
    $terminal = $(terminal);
    return $el.data('Termic', Termic.prototype.constructer($el[0], $terminal[0], commands));
  };

}).call(this);
